<a href="https://colab.research.google.com/github/shubham-7745/PDS-Assignment/blob/main/practical2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Name  :- Shubham Matsagar
Roll no :- 05
Class :- SY B

Practical 2

Aim - 	Data Ingestion and Cleaning: Acquire data and prepare it for analysis.

### Answers to the Questions:

1.  **What is data ingestion and why is it important in data science? Which Python library is commonly used for data ingestion and cleaning?**

    *   **Data Ingestion**: Data ingestion is the process of importing and transferring data from one or more sources into a system where it can be stored, processed, and analyzed. This often involves collecting data from various formats (databases, APIs, files, streams) and bringing it into a data processing pipeline or storage.
    *   **Importance**: It's crucial in data science because it's the first step in any data-driven project. Without proper data ingestion, there's no data to analyze, build models with, or extract insights from. It sets the foundation for all subsequent steps.
    *   **Common Python library**: The `pandas` library is very commonly used for data ingestion (e.g., reading CSV, Excel, SQL databases) and initial cleaning tasks in Python.

2.  **Why is data cleaning necessary before performing analysis or machine learning?**

    Data cleaning is essential because real-world data is often messy, inconsistent, and incomplete. Neglecting data cleaning can lead to:
    *   **Inaccurate results**: Errors, outliers, or missing values can skew statistical analysis and model predictions.
    *   **Misleading insights**: Conclusions drawn from dirty data might be incorrect or not representative of the true underlying patterns.
    *   **Model performance degradation**: Machine learning models trained on unclean data can perform poorly, fail to converge, or produce unreliable outputs.
    *   **Increased complexity**: Handling dirty data during analysis or modeling is often more complex and time-consuming than cleaning it upfront.

3.  **How do you load a CSV file into a Pandas DataFrame?**

    You can load a CSV file into a Pandas DataFrame using the `pd.read_csv()` function. Here's an example:
    ```python
    import pandas as pd

    df = pd.read_csv('your_file_name.csv')
    print(df.head())
    ```
    Replace `'your_file_name.csv'` with the actual path to your CSV file.

4.  **What is the difference between head() and tail() functions in Pandas?**

    Both `head()` and `tail()` are DataFrame methods used to quickly inspect a DataFrame:
    *   `df.head(n)`: Returns the **first `n` rows** of the DataFrame. By default, `n` is 5.
    *   `df.tail(n)`: Returns the **last `n` rows** of the DataFrame. By default, `n` is 5.

    They are useful for getting a quick overview of the data's structure and content from both ends.

5.  **How can you identify missing values in a dataset?**

    In Pandas, you can identify missing values using several methods:
    *   `df.isnull()` or `df.isna()`: These methods return a boolean DataFrame of the same shape as the original DataFrame, indicating `True` where a value is missing (NaN, None, NaT) and `False` otherwise.
    *   `df.isnull().sum()`: This is commonly used to get a count of missing values for each column.
    *   `df.isnull().sum().sum()`: This will give you the total number of missing values across the entire DataFrame.
    *   `df.info()`: This method provides a concise summary of a DataFrame, including the number of non-null values for each column, which can help quickly spot columns with missing data.

    Example:
    ```python
    import pandas as pd
    import numpy as np

    data = {'A': [1, 2, np.nan, 4],
            'B': [5, np.nan, 7, 8],
            'C': [9, 10, 11, 12]}
    df = pd.DataFrame(data)

    print("\nBoolean DataFrame for nulls:")
    print(df.isnull())

    print("\nMissing values count per column:")
    print(df.isnull().sum())

    print("\nTotal missing values in DataFrame:")
    print(df.isnull().sum().sum())

    print("\nDataFrame info:")
    df.info()
    ```

In [ ]:
Code

### Data Ingestion and Cleaning Implementation

First, let's create a dummy CSV file to simulate real-world data. This will allow us to demonstrate data ingestion and cleaning techniques.

In [ ]:
import pandas as pd
import numpy as np

# Create a dummy dataset with some missing values and mixed data types
data = {
    'ProductID': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    'ProductName': ['Laptop', 'Mouse', 'Keyboard', 'Monitor', 'Speaker', 'Webcam', 'Microphone', 'Headphones', 'Printer', 'Router'],
    'Category': ['Electronics', 'Electronics', 'Electronics', 'Electronics', 'Electronics', 'Accessories', 'Accessories', 'Accessories', 'Peripherals', 'Networking'],
    'Price': [1200.00, 25.50, 75.00, 300.00, np.nan, 35.00, 50.00, 99.00, 250.00, 80.00],
    'QuantitySold': [10, 150, 80, 20, 50, np.nan, 60, 40, 15, 30],
    'DateSold': ['2023-01-01', '2023-01-05', '2023-01-08', '2023-01-10', '2023-01-12', '2023-01-15', '2023-01-18', '2023-01-20', '2023-01-22', '2023-01-25'],
    'CustomerRating': [4.5, 4.0, 4.2, 4.8, 3.9, np.nan, 4.1, 4.6, 3.5, 4.7]
}

df_raw = pd.DataFrame(data)

# Introduce some more missing values randomly for demonstration
df_raw.loc[2, 'Category'] = np.nan
df_raw.loc[7, 'ProductName'] = np.nan

# Save to a CSV file
dummy_csv_path = 'dummy_sales_data.csv'
df_raw.to_csv(dummy_csv_path, index=False)

print(f"Dummy CSV file '{dummy_csv_path}' created successfully.")

Dummy CSV file 'dummy_sales_data.csv' created successfully.

### 1. Data Ingestion: Loading the CSV file

In [ ]:
# Load the dummy CSV file into a Pandas DataFrame
df = pd.read_csv(dummy_csv_path)

print("DataFrame loaded successfully. Displaying the first 5 rows:")
display(df.head())

DataFrame loaded successfully. Displaying the first 5 rows:

,ProductID,ProductName,Category,Price,QuantitySold,DateSold,CustomerRating
0,101,Laptop,Electronics,1200.0,10.0,2023-01-01,4.5
1,102,Mouse,Electronics,25.5,150.0,2023-01-05,4.0
2,103,Keyboard,NaN,75.0,80.0,2023-01-08,4.2
3,104,Monitor,Electronics,300.0,20.0,2023-01-10,4.8
4,105,Speaker,Electronics,NaN,50.0,2023-01-12,3.9

### 2. Initial Data Inspection

In [ ]:
# Get a concise summary of the DataFrame, including data types and non-null values
print("DataFrame Info:")
df.info()

print("\nMissing values count per column:")
# Identify missing values
missing_values_count = df.isnull().sum()
display(missing_values_count)

print("\nTotal missing values in the DataFrame:")
total_missing = df.isnull().sum().sum()
print(total_missing)

DataFrame Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   ProductID       10 non-null     int64
 1   ProductName     9 non-null      object
 2   Category        9 non-null      object
 3   Price           9 non-null      float64
 4   QuantitySold    9 non-null      float64
 5   DateSold        10 non-null     object
 6   CustomerRating  9 non-null      float64
dtypes: float64(3), int64(1), object(3)
memory usage: 692.0+ bytes

Missing values count per column:

ProductID         0
ProductName       1
Category          1
Price             1
QuantitySold      1
DateSold          0
CustomerRating    1
dtype: int64

Total missing values in the DataFrame:
5

### 3. Data Cleaning: Handling Missing Values and Data Type Conversion

In [ ]:
# Convert 'DateSold' to datetime objects
df['DateSold'] = pd.to_datetime(df['DateSold'])

# Fill missing 'Price' values with the median price
median_price = df['Price'].median()
df['Price'].fillna(median_price, inplace=True)

# Fill missing 'QuantitySold' with the mean quantity
mean_quantity = df['QuantitySold'].mean()
df['QuantitySold'].fillna(mean_quantity, inplace=True)

# For categorical columns like 'ProductName' and 'Category', we can fill with the mode or a placeholder
# Here, we'll fill with 'Unknown' for demonstration
df['ProductName'].fillna('Unknown', inplace=True)
df['Category'].fillna('Unknown', inplace=True)

# For 'CustomerRating', let's fill with the mean rating
mean_rating = df['CustomerRating'].mean()
df['CustomerRating'].fillna(mean_rating, inplace=True)

print("DataFrame after handling missing values and converting 'DateSold':")
df.info()

print("\nMissing values count after cleaning:")
display(df.isnull().sum())

print("\nCleaned DataFrame head:")
display(df.head())

DataFrame after handling missing values and converting 'DateSold':
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   ProductID       10 non-null     int64
 1   ProductName     10 non-null     object
 2   Category        10 non-null     object
 3   Price           10 non-null     float64
 4   QuantitySold    10 non-null     float64
 5   DateSold        10 non-null     datetime64[ns]
 6   CustomerRating  10 non-null     float64
dtypes: datetime64[ns](1), float64(3), int64(1), object(2)
memory usage: 692.0+ bytes

Missing values count after cleaning:

/tmp/ipykernel_6430/2506379179.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Price'].fillna(median_price, inplace=True)
/tmp/ipykernel_6430/2506379179.py:10: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['QuantitySold'].fillna(mean_quantity, inplace=True)
/tmp/ipykernel_6430/2506379179.py:14: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['ProductName'].fillna('Unknown', inplace=True)
/tmp/ipykernel_6430/2506379179.py:15: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Category'].fillna('Unknown', inplace=True)
/tmp/ipykernel_6430/2506379179.py:19: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['CustomerRating'].fillna(mean_rating, inplace=True)

ProductID         0
ProductName       0
Category          0
Price             0
QuantitySold      0
DateSold          0
CustomerRating    0
dtype: int64

Cleaned DataFrame head:

,ProductID,ProductName,Category,Price,QuantitySold,DateSold,CustomerRating
0,101,Laptop,Electronics,1200.0,10.0,2023-01-01,4.5
1,102,Mouse,Electronics,25.5,150.0,2023-01-05,4.0
2,103,Keyboard,Unknown,75.0,80.0,2023-01-08,4.2
3,104,Monitor,Electronics,300.0,20.0,2023-01-10,4.8
4,105,Speaker,Electronics,80.0,50.0,2023-01-12,3.9

Conclusion he data ingestion and cleaning process is now complete. We successfully created a dummy dataset, loaded it, identified and handled missing values across various columns (Price, QuantitySold, ProductName, Category, CustomerRating), and ensured the 'DateSold' column was correctly formatted as datetime objects. The dataset is now clean and prepared for further analysis, visualization, or machine learning tasks.